algo_configs={
    "story_parse":{
        "model":"gpt",
        "prompt_type":"structure_parse"
    },
    "story_translate":{
        "model":"deepseek-v3-apicore",
    },
    "story_quality_eval":{
        "model":"deepseek-v3-apicore",
        "prompt_type":"story_quality_eval"
    },
}